kind: pipeline
name: default

steps:
  - name: FrontEnd Eval
    image: node
    commands:
      - npm install
      - npm install -g enzyme
      - npm install -g jest
      - npm install -g enzyme-adapter-react-16
      - git clone https://github.com/unsortedArray/Hackathon2308FECASES.git
      - cd Hackathon2308FECASES
      - enzyme EnzymeCases.js 
      - jest Yest.js
